### PR TITLE
Add pmml-notebook and review README.md of the project

### PR DESCRIPTION
**Pull request by danielezonca**
Create notebook to explain how to train and export a model as PMML

### CODE REVIEW

**Comment by ruivieira** [comment]
@danielezonca lgtm!

Just a few minor comments:

- Perhaps it would be easier to provide all the dependencies in a `requirements.txt` and instruct the user to run `pip install -r requirements.txt`
- If you don't want very high model score, introduce a small amount of randomness in `disp_risk` (for instance, `return 2 if random()<0.9 else 1` instead of `return 2`).
- Add a `plt.show()` and the end of the cell for the plot to remove the `__repr__` echo.

**Review by ruivieira — APPROVED** [review]

**Review by tarilabs — COMMENTED** [review]
Thanks Daniele, overall looks good to me! 
Personally, in this notebook I would give the data "for granted" coming from a CSV file.

For example, in most Kaggle notebook there is:

- an Intro like you have,
- a ["Data exploration" section(example)](https://www.kaggle.com/tentotheminus9/what-causes-heart-disease-explaining-the-model#The-Data) --where you actually have a generate test data section instead
- Model build
- XAI, etc as you do here.

For this being an instructive hello-world tutorial, I would indeed give the CSV or "train data" for granted.
I believe it will be helpful to keep in the same directory the notebook with the python code to generate the data too.

Hope this helps!

**Comment by danielezonca** [comment]
@ruivieira 
Thanks for the suggestions :)

> * Perhaps it would be easier to provide all the dependencies in a `requirements.txt` and instruct the user to run `pip install -r requirements.txt`

Done
> * If you don't want very high model score, introduce a small amount of randomness in `disp_risk` (for instance, `return 2 if random()<0.9 else 1` instead of `return 2`).

Done
> * Add a `plt.show()` and the end of the cell for the plot to remove the `__repr__` echo.

Done

@tarilabs 
Thanks for the suggestion, I moved data generation to a separated script and committed the generated file so now the notebook will just load an existing CSV file as you proposed :+1:

**Review by tarilabs — APPROVED** [review]
I like indeed how the [new section](https://render.githubusercontent.com/view/ipynb?commit=123e5792ac09462f52bfb3f8bb6dd1c552c7f0f1&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6b696567726f75702f7472757374792d61692d73616e64626f782f313233653537393261633039343632663532626662336638626236646431633535326337663066312f706d6d6c2d6e6f7465626f6f6b2f6e6f7465626f6f6b2e6970796e62&nwo=kiegroup%2Ftrusty-ai-sandbox&path=pmml-notebook%2Fnotebook.ipynb&repository_id=251593561&repository_type=Repository#Step-1---Load-and-prepare-data) results in the final notebook result, thanks!

**Review by tteofili — APPROVED** [review]
LGTM

**Pull request merged**
